---
title: "<br>An Introduction the Shell"
output:
  rmarkdown::html_document:
    theme: cerulean
    css: my.css
---

<br>

> ## Learning Objectives
>
> * Learn what the shell is and why you would want to use it.
> * In the shell, learn how to:
>   * Navigate
>   * Organize and examine files
>   * Manage input and output streams
> * Bonus: Learn how to submit a shell script as a job at OSC

------------

## <a href="slides/02-shell-slides.html" target="_blank">Click here for the slides</a>


**Or jump straight to a section within the slides:**

- [Introduction](slides/02-shell-slides.html#intro)
- [Navigation](slides/02-shell-slides.html#navigation)
- [Standard In/Out and Pipes](slides/02-shell-slides.html#stdin)
- [Managing Files](slides/02-shell-slides.html#managing_files)
- [Wildcards](slides/02-shell-slides.html#wildcards)
- [Viewing Text Files](slides/02-shell-slides.html#text_files)
- [Variables and Scripts](slides/02-shell-slides.html#script)
- [Bonus Material](slides/02-shell-slides.html#bonus)
  - I: [Keyboard Shortcuts and General Tricks](slides/02-shell-slides.html#tricks)
  - II: [Text File Data Tools](slides/02-shell-slides.html#datatools)
  - III: [The `less` Pager](slides/02-shell-slides.html#less)
  - IV: [Standard Error](slides/02-shell-slides.html#stderr)

<br> <br> <br> <br>
