---
title: "<br>An Introduction to the<br>Ohio Supercomputer Center (OSC)"
output:
  rmarkdown::html_document:
    theme: cerulean
    css: my.css
---

<br>

> ## Learning Objectives
>
> * Learn what the OSC is and why you may want to use it.
> * Learn how to connect to OSC through the OnDemand portal.
> * Learn how to transfer data to and from OSC.
> * Understand the difference between login and compute nodes.
> * Understand several important options when submitting a compute job.
> * Learn about software availability at OSC.
> * Get a taste for command-line options at OSC.

------------

## <a href="slides/03-OSC-slides.html" target="_blank">Click here for the slides</a>


**Or jump straight to a section within the slides:**

- [Introduction](slides/03-OSC-slides.html#introduction)
- [Connecting to OSC](slides/03-OSC-slides.html#connect)
- [Transferring Files](slides/03-OSC-slides.html#transfer)
- [Software at OSC](slides/03-OSC-slides.html#software)
- [Starting a Compute Job](slides/03-OSC-slides.html#jobs)
- [Compute Job Options](slides/03-OSC-slides.html#job_options)
- [Bonus Material](slides/03-OSC-slides.html#bonus)
  - I: [OSC File Systems](slides/03-OSC-slides.html#filesystems)
  - II: [Accessing OSC In Your Shell (`ssh`)](slides/03-OSC-slides.html#shell)
  - III: [Monitoring *SLURM* Jobs](slides/03-OSC-slides.html#monitor)
  - IV: [More on Software at OSC](slides/03-OSC-slides.html#conda)

<br> <br> <br>
